# -*- coding: utf-8 -*-
"""user_input.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S07SIJmjWupgyt-e7DkkBeVSlGfI_4eY
"""

name = 'John'
age = 18
location = 'Nairobi'
print(f'Hello {name}, you are {age} years old and live in {location}.')